name: Build and Deploy Frontend to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js (v18)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar Dependências e Compilar com Vite
        run: |
          cd frontend
          npm install
          npm run build
        env:
            VITE_API_URL: ${{ secrets.VITE_API_URL }}

      - name: Enviar para o Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './frontend/dist'