name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install and build
        run: |
          npm install
          npm run build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: frontend/dist  # ← Só o dist/, não a pasta inteira com node_modules

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./dist

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7DAEABDC4FA546AB8B18495388A9D8FC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3735BCBC497B40188B48A0EE6EFE1563 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E421EC468CD34F39BC04E5980F6C91C4 }}

      - name: Zip the dist folder
        run: |
          cd ./dist
          zip -r ../app.zip .
          cd ..

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-securitest-frontend-16ntg2'
          slot-name: 'Production'
          package: ./app.zip